### ISSUE TITLE
Tickets Transfer

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#21]
Tickets Transfer process

**Comment by ananyo2012** [comment]
- Create a spreadsheet to track transfer requests
- Requestor email, Receiver email, Payment Done - these should be the fields
- Collect Receiver details
- Once payment is confirmed by requestor we can transfer the ticket to the Receiver using Transfer button in Konfhub

@anistark Hope this helps.

**Comment by anistark** [comment]
This is pushed out.
