### ISSUE TITLE
Community Partners

### ISSUE THREAD

**Issue by tankala** [pythonindia/inpycon2024-tasks#36]
Tasks

### Navigator @anistark 
- [x] Add Community partner program content to https://in.pycon.org/navigator/. Ref: https://drive.google.com/file/d/17P7CaYvOghF8WGm1QtVT6jK162SyTBph/view

### Website @bhansa 
- [ ] Provision to add Community partners' logos on the website.

### Content WG @Sc0rpi0n101 :
- [x] Content for announcement for community partners program
  - [x] Mail 
  - [x] Social Media
- [x] Content for reaching out inviting to be community partner

### Comms WG @bhansa @WatchfulHitman 
- [x] Form to submit their details to become a Community partner. - https://dub.sh/inpy24com
- [x] Probable Community partners list (https://docs.google.com/spreadsheets/d/1KNphdfEjTw7n-vQ7mNgClR5ssAVdL0SuIBb6tJ4fVPQ/edit#gid=0)
- [x] Inform personally to Preferred community partners about "Community partners program"

### Announcement of community partners program in Social Media @WatchfulHitman 
- [x] Inpycon Mailing List
- [x] X-Post on other mailing lists
- [x] Twitter
- [x] LinkedIn
- [x] Facebook
- [x] Instagram
- [x] Mastodon

### Reach out to Community Partners @tankala
- [x] Active Last year ones
- [x] From the list we created

**Comment by tankala** [comment]
@anistark created the form - https://dub.sh/inpy24com

**Comment by anistark** [comment]
[Navigator is live](https://in.pycon.org/navigator/participate/community-partner.html)

**Comment by harisibrahimkv** [comment]
Content: https://github.com/pythonindia/inpycon-blog/issues/445
