### ISSUE TITLE
[CFP] Reachout to previous years speakers about CFP

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#39]
Invite previous years speakers to submit talk/workshop this year.
It's highly likely that they might do submit again.

**Comment by muralinmc** [comment]
Dear  …….

Greetings from Pycon India 2024 

We Thank you for being a speaker in the last edition in Hyderabad.  Your contribution to the community is really awesome and we expect that you may continue to share your expertise to the community in the years to come.  As like last year , this year we are going to convene Pycon India  2024 from 20th September 2024 at Bangalore. The CFP invite is rolled out and it is in progress. We would like to invite you to submit proposals this year also. The last date for submission is on 31.05.2024.
The link is given below for your reference.


Expecting your participation in the conference eagerly


Thanking You


_________
Volunteer
CFP WG


is this template is OK 
@anistark
I will assign this task to Pavan BG (gpavanb1)

**Comment by gpavanb1** [comment]
I have sent this out. Also included CFP email as receiver
