### ISSUE TITLE
Content for community partner on boarding

### ISSUE THREAD

**Issue by tankala** [pythonindia/inpycon2024-tasks#44]
@Sc0rpi0n101 
We are going to onboard communities to our Community partner program.
For them, we need to send welcome mail. Please help us in preparing it.

**Comment by harisibrahimkv** [comment]
I'm assuming this task is related to already having a few communities signed up and us wanting to tell them "what" we are going to do together and "how" we are going to do it?

**Comment by tankala** [comment]
Yes. You can find details here - https://navigator.in.pycon.org/en/latest/participate/community-partner.html

**Comment by harisibrahimkv** [comment]
@tankala That's exactly the same as what we have here: https://github.com/pythonindia/inpycon-blog/issues/445

Is that what you're looking for? I would assume the welcome mail is for those have signed up and hence to specifically give action items on what to do when.

Please correct me if I am wrong.
