### ISSUE TITLE
[WG CFP] Public Voting

### ISSUE THREAD

**Issue by muralinmc** [pythonindia/inpycon2024-tasks#45]
**To discuss and decide whether we can remove the public voting system in the junction for the proposals as we are not using them for selecting the talks 
(or) we can keep them as it is**
Note:
Submitters asked some query's in this regard. 

[](https://in.pycon.org/cfp/2024/proposals/)

- [] <Discussion> **Discussion**  @anistark @bhansa @wavicles @sayanchowdhury @bhavin192 @palnabarun

**Comment by anistark** [comment]
You can create a [discussion](https://github.com/pythonindia/inpycon2024-tasks/discussions) instead.

**Comment by muralinmc** [comment]
Created a discussion 
https://github.com/pythonindia/inpycon2024-tasks/discussions
