### ISSUE TITLE
[Comms] CFP Poster & BoF Reminder Post Review

### ISSUE THREAD

**Issue by WatchfulHitman** [pythonindia/inpycon2024-tasks#50]
CONTENT for Review:

🚨 Attention Pythonistas 🐍

Don't forget: BoF & CFP Poster Presentation submissions for #PyConIndia2024 are still open!

Showcase your ideas and connect with the community. Seize this opportunity to shine ✨

Submit now 🔗 http://in.pycon.org/bof

#python

![BoF-Rem2](https://github.com/user-attachments/assets/7cb045e3-6605-4271-81da-82cb3da51cf9)

Announcement Date: 23rd July 5:00 PM, 2024

## Tasks
- [ ] review of the above content, @sayanchowdhury @rayandas @kalyan678 @palnabarun 

### Pre 4PM
- [ ] review of the above content, @sayanchowdhury @rayandas @kalyan678 @palnabarun

**Comment by kalyan678** [comment]
@WatchfulHitman - I slightly rephrased the content. Here's the one:


🚨 Attention Python enthusiasts

BoF and Poster Presentation submissions for #PyConIndia2024 are still open! Share your ideas and connect with the community. Don’t miss your chance to shine ✨

**Comment by WatchfulHitman** [comment]
**updated content**

🚨 Attention Pythonistas 🐍

Reminder: BoF and Poster Presentation submissions for #PyConIndia2024 are still open! 

Share your ideas and connect with the community. Don’t miss your chance to shine ✨

Submit now 🔗 http://in.pycon.org/bof

#python

**Comment by WatchfulHitman** [comment]
**new poster**

![BoF-Reminder2](https://github.com/user-attachments/assets/28820c4a-c812-465d-afc7-da68165f020a)

**Comment by iamaravindsekar** [comment]
Made some changes and updated the poster for this announcement, Putting that here for review. ![IMG-20240723-WA0002.jpg](https://github.com/user-attachments/assets/a46c9d5a-f1b9-40bf-977a-a8ebf886ce61)

**Comment by iamaravindsekar** [comment]
If this is good to go, I have uploaded the original file to Google drive, and it can be downloaded from there. Thank you . https://drive.google.com/file/d/18T3z0mLtsugkJQgk9oeSTH3duYVI2oQv/view?usp=share_link

**Comment by WatchfulHitman** [comment]
Post completed hence closed
