### ISSUE TITLE
[Comms] Mail Content for Cancellation post

### ISSUE THREAD

**Issue by WatchfulHitman** [pythonindia/inpycon2024-tasks#52]
**Mail Content**

Subject: Ticket Cancellations are live

Hi Everyone,

Ticket cancellations are now live.

If you have booked your tickets earlier and now have a change in your plans, you can cancel them by writing to us at tickets@in.pycon.org. The deadline for cancellations is August 14th, 2024, at 11:59 PM IST.

No cancellations will be entertained after the specified deadline. To know more about the cancellation process, you can visit our website's FAQ section [0].

If you have any concerns regarding the above, please feel free to write us at tickets@in.pycon.org or reach out to any of us on Zulip [1].

[0] https://in.pycon.org/2024/faq/
[1] https://pyconindia.zulipchat.com/

With regards,

<name>

On behalf of the PyCon India 2024 Team

https://in.pycon.org/2024/

Announcement Date: 22nd July 5:30 PM, 2024

## Tasks
- [ ] Mailing to be done to all mailing lists, @tankala

**Comment by tankala** [comment]
Mail sent

**Comment by WatchfulHitman** [comment]
Mail is sent hence issue is closed.
