### ISSUE TITLE
[Comms] Associate Sponsor : Reckonsys Tech Labs

### ISSUE THREAD

**Issue by WatchfulHitman** [pythonindia/inpycon2024-tasks#65]
Review of Content:

Riseup Pad : https://pad.riseup.net/p/yBRh3bQnvxUUpN7PufbL

logo: https://drive.google.com/file/d/1EPp6CYqfZFdlrBImt3Q5csDgc95385QI/view

poster: 
![Associate Sponsor-Reckonsys](https://github.com/user-attachments/assets/3cb9751b-5af2-4023-bd91-5c9dd6567949)

## Tasks
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ]  Blog Creation, @Sc0rpi0n101, @harisibrahimkv 
- [ ]  Posting of blog on website, @bhansa @vamc-k
- [ ]  Poster Creation, @iamaravindsekar

### Pre 4PM
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ]  Blog Creation, @Sc0rpi0n101, @harisibrahimkv 
- [ ]  Posting of blog on website, @bhansa @vamc-k
- [ ]  Poster Creation, @iamaravindsekar

### Post 5PM
- [ ] posting content and mailing, @WatchfulHitman @tankala

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by vamc-k** [comment]
Website PR: pythonindia/inpycon2024/pull/61
