### ISSUE TITLE
[Comms] Announcing Next Silver Sponsor: FireDucks

### ISSUE THREAD

**Issue by WatchfulHitman** [pythonindia/inpycon2024-tasks#66]
Review the content

Riseup Pad Link: https://pad.riseup.net/p/P_POutayr0k54FbzgMdT

Logo: https://drive.google.com/file/d/1c4GNSryH-s6OVACjTvDCVM8l9roKowo3/view

Poster: 
![Silver Sponsor-Fireducks](https://github.com/user-attachments/assets/b532d29f-bd46-4cd8-8e1e-7ac8b4307795)

## Tasks
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ] Blog Creation, @Sc0rpi0n101 @harisibrahimkv
- [ ]  Posting of blog on website, @bhansa @vamc-k
- [ ]  Poster Creation, @iamaravindsekar

### Pre 4PM
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ] Blog Creation, @Sc0rpi0n101 @harisibrahimkv
- [ ]  Posting of blog on website, @bhansa @vamc-k
- [ ]  Poster Creation, @iamaravindsekar

### Post 5PM
- [ ] posting content and mailing, @WatchfulHitman @tankala 

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by anistark** [comment]
Blog PR: https://github.com/pythonindia/inpycon-blog/pull/465

**Comment by vamc-k** [comment]
Website PR: pythonindia/inpycon2024#60
