### ISSUE TITLE
Red Hat - Associate sponsor

### ISSUE THREAD

**Issue by palnabarun** [pythonindia/inpycon2024-tasks#68]
Review the content

Riseup Pad Link: TBD

Logo: TBD

Poster: TBD

## Tasks
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ] Blog Creation, @Sc0rpi0n101 @harisibrahimkv
- [ ]  Posting of blog on website, @bhansa @vamc-k
- [ ]  Poster Creation, @iamaravindsekar

### Pre 4PM
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ] Blog Creation, @Sc0rpi0n101 @harisibrahimkv
- [ ]  Posting of blog on website, @bhansa @vamc-k
- [ ]  Poster Creation, @iamaravindsekar

### Post 5PM
- [ ] posting content and mailing, @WatchfulHitman @tankala 

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by WatchfulHitman** [comment]
https://github.com/pythonindia/inpycon2024-tasks/issues/80

**Comment by anistark** [comment]
This is done.
