### ISSUE TITLE
[Comms] Speaker and Talk+Workshop announcement/promotion

### ISSUE THREAD

**Issue by bhavin192** [pythonindia/inpycon2024-tasks#69]
We want to announce our speakers and their talks on social media, each **talk/workshop** can have a poster which we share over the social media. 

Example from last year:
- https://x.com/pyconindia/status/1705892330451128376 (they did two posters at once, we can do one at a time also as we have some time till conference).

## Tasks
- [ ] Create poster for all the talks + workshops, design wg (total: 36).
- [ ] Announce all these talks and workshops on social media.

### How to interpret the sheet
I have shared a sheet with @WatchfulHitman and @iamaravindsekar here are things:
- The ones marked with green in title have two speakers for the same talk, this should be single poster/image.
- There are things to be mindful about marked in red, these are some requests made by speakers. 
  - _@WatchfulHitman you can use the sheet's Q column onward to write social media messages and get it reviewed from others, that way everything remain at a single place._
- _If speaker's photo is not available, can check their LinkedIn/social media profiles and use photo from there. If no social media links are given, the image/poster can be just the talk title :)_ 

## Timeline
Can be started from ~~2nd~~ 9th September onward and finish it over 10 days or so? Something the Comms wg can take a decision on. 

### Communication Channel (if needed for your task)

~~- [ ] Mailing List~~
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by bhavin192** [comment]
Based on discussion in the weekly call:

- We will start with this from 9th September, Monday. 
- Plan to do 6 posts a day. 
- Only social media posts will go out. No email is required.

**Comment by WatchfulHitman** [comment]
Review of content: https://pad.riseup.net/p/AjAkMVoNnv8wS69HXdNa

@sayanchowdhury @bhavin192 @rayandas @palnabarun @kalyan678 @Sc0rpi0n101 @harisibrahimkv

**Comment by samarpitasaha** [comment]
@WatchfulHitman You can find the speaker posters here: 
https://drive.google.com/drive/folders/1yFrCR-a9-CL57wzX6JN6RKBKfaSaVpxC?usp=sharing

We have uploaded 15 posters for now, and we are working on the rest of the posters.
cc: @bhavin192

**Comment by anistark** [comment]
This is done.
