### ISSUE TITLE
[Design] Badge

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#70]
4 types:

1. Sponsor
2. Attendee
3. Speaker
4. Volunteer

[QR link](https://in.pycon.org/2024/schedule/)

Platinum Sponsor logos

Font figure out alternates.

**Comment by iamaravindsekar** [comment]
Badge designs completed, Badges generated for all types of attendees, Designs were delivered to the print vendor and this issue can be closed if we are good here.
