### ISSUE TITLE
[Design] Banner

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#75]
12ft W x 8ft H

- [ ] Main Banner
- [ ] Schedule

**Comment by Eaarjun** [comment]
@anistark Hello, you can find the schedule banner over here.
https://drive.google.com/drive/folders/1tOenKMdHg_jRqDSXpqznHYF_6IuPD4bp?usp=drive_link

**Comment by iamaravindsekar** [comment]
We are good with this and the issue can be closed
