### ISSUE TITLE
[Design] Standees

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#76]
3ft W x 6ft H 

- [ ] Parking Direction (1)
- [ ] After Main gate near lawn - Main Standee
- [ ] 3 track in workshop (1)
- [ ] track schedule (3 - each in front of each hall)
- [ ] CoC (4)
- [ ] Food Area direction (1)
- [ ] Childcare (1)
- [ ] PyLadies Lunch (1)

**Comment by iamaravindsekar** [comment]
All standees completed and this issue can be closed.
