### ISSUE TITLE
Track Pratik Deliverables 

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2024-tasks#86]
- [ ] Google sheet for Track Host, and Speaker Coordinator
- [ ] Registration Desk
- [ ] Roles for every volunteers responsiblity document in Navigator.

**Comment by pratik-anurag** [comment]
Changes done in the sheet, have shared a doc with volunteers roles and responsibilities for initial review. Will open a pr to navigator.
